spring.application.name=CustomerServicePortal
server.port=8619

# Edit this to 'local' for locally hosted db, and 'cloud' for cloud hosted db
spring.profiles.active=local

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true